### ISSUE TITLE
Attempted to read or write protected memory. This is often an indication that other memory is corrupt

### ISSUE THREAD

**Issue by i2i8** [AonaSuzutsuki/ExRegistryHive#2] opened 2021-09-16 19:30 UTC
When I set the key value and run the program, I will be prompted as follows:
**Attempted to read or write protected memory. This is often an indication that other memory is corrupt**
But in fact, the key has already been successfully written to the registry,
Excuse me, how to solve this problem?

**Comment by AonaSuzutsuki** [comment] 2021-09-17 00:16
I ran the sample and it worked fine.
The verification environment is "Windows 10 x64 20H2 19042.1165".
I don't know it, because I can't reproduce it...

If you are using "ExRegistryHiveLib", you may need to modify it.
I haven't updated it in a long time, and I think it has a lot of flaws.
I'm sorry, I haven't updated the site in a long time, so I don't know the details.

...

For you information,  
Also you will not be able to operate Hive if you exit the program before releasing it. In that case, please use regedit.exe to unload it.

**Comment by AonaSuzutsuki** [comment] 2021-09-26 13:08
This is a thread that hasn't been running for a long time, so I'm closing it.

**Closed as completed by AonaSuzutsuki** 2021-09-26 13:08 UTC
